<?php
$listarray = array ( array ( 'label' => 'Rezept',
                             'name' => 'rezept', 
                             'width' => 200, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_rezepte' ),
                     array ( 'label' => 'Menge',
                             'name' => 'menge', 
                             'width' => 100, 
                             'type' => 'zahl',
                             'dbfield' => 'fldmenge' ),
                     array ( 'label' => 'ME',
                             'name' => 'me', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblmengein',
                             'seldbfield' => 'fldkurz',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_me' ),
                     array ( 'label' => 'Zutat',
                             'name' => 'zutat', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Kalorien',
                             'name' => 'kalorien', 
                             'width' => 100, 
                             'type' => 'calc',
                             'fieldhide' => 'true',
                             'nachkomma' => '0',
                             'calcfield' => 'fldmenge',
                             'dbfield' => 'fldkalorien' ),
                     array ( 'label' => 'Grundartikel',
                             'name' => 'grundartikel', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblgrundartikel',
                             'seldbfield' => 'fldbezmz',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_grundartikel' ),
                     array ( 'label' => 'kcal',
                             'name' => 'kcal', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'fieldsave' => 'NO',
                             'dbtable' => 'tblgrundartikel',
                             'seldbfield' => 'fldkalorien',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_grundartikel' ),
                     array ( 'label' => 'Faktor',
                             'name' => 'faktor', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'fieldsave' => 'NO',
                             'dbtable' => 'tblgrundartikel',
                             'seldbfield' => 'fldfaktor',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_grundartikel' ),
                     array ( 'label' => 'kcal (Summe)',
                             'name' => 'kcalmul', 
                             'width' => 100, 
                             'type' => 'zahlmult',
                             'columnarr' => '2,6,7',
                             'dbfield' => 'flddummy' ));

$filterarray = array ( array ( 'label' => 'Rezept',
                             'name' => 'rezept', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_rezepte' ));

$pararray = array ( 'headline' => 'Zutaten',
                    'dbtable' => 'tblzutaten',
                    'subtitle' => 'true',
                    'subdbtable' => 'tblrezepte',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');

?>