<?php
$listarray = array ( array ( 'label' => 'Vorname',
                             'name' => 'vorname', 
                             'width' => 150, 
                             'type' => 'text',
                             'dbfield' => 'fldVorname' ),
                     array ( 'label' => 'Nachname',
                             'name' => 'nachname', 
                             'width' => 150, 
                             'type' => 'text',
                             'dbfield' => 'fldNachname' ),
                     array ( 'label' => 'Geburtstag',
                             'name' => 'geburtstag', 
                             'width' => 100, 
                             'type' => 'date',
                             'dbfield' => 'fldGebDatum' ),
                     array ( 'label' => 'Alter',
                             'name' => 'alter', 
                             'width' => 40, 
                             'type' => 'age',
                             'dbfield' => 'fldGebDatum' ),
                     array ( 'label' => 'Status',
                             'name' => 'status', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_status' ));

$filterarray = array (array ( 'label' => 'nur aktuelle',
                             'name' => 'nuraktuelle', 
                             'width' => 10, 
                             'type' => 'text',
                             'default' => 'now()',
                             'sign' => '>=',
                             'dbfield' => 'fldSort' ),
                     array ( 'label' => 'Status:',
                             'name' => 'fltstatus', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_status' ));


$pararray = array ( 'headline' => 'Geburtstage',
                    'dbtable' => 'tblgeburtstage',
                    'orderby' => 'month(fldGebDatum),day(fldGebDatum),fldSort',
//                    'strwhere' => 'fldSort>=substr(current_date(),6,5)',
                    'fldindex' => 'fldIndex',
                    'marktype' => 'date',
                    'markbgcolor' => '88ffff',
                    'unmarkbgcolor' => '999fff',
                    'marksuccess' => '1938-01-16',
                    'marksign' => '=',
                    'markfield' => 'fldGebDatum');
?>