<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'name' => 'nr', 
                             'width' => 20, 
                             'type' => 'nummer',
                             'dbfield' => 'flddummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Betrag',
                             'name' => 'betrag',
                             'width' => 70, 
                             'type' => 'calc',
                             'dbfield' => 'fldbetrag' ),
                     array ( 'label' => 'Konto',
                             'name' => 'konto',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblktokonten',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'seldborder' => 'fldBez',
                             'dbfield' => 'fldid_kto' ),
                     array ( 'label' => 'Dauerauftragtyp',
                             'name' => 'dauerauftragtyp',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tbldauerauftragtyp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_dauerauftragtyp' ),
                     array ( 'label' => 'Kontoinhaber',
                             'name' => 'gruppe',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblktobanken',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_ktogrp' ),
                     array ( 'label' => 'KontoEATyp',
                             'name' => 'ktoeatyp',
                             'width' => 20, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblktoEATyp',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_ktoeatyp' ),
                     array ( 'label' => 'F&aumlllig:',
                             'name' => 'fldfaellig',
                             'width' => 20, 
                             'type' => 'date',
                             'dbfield' => 'fldfaelligdatum' ),
                     array ( 'label' => 'Anz Monate:',
                             'name' => 'fldanzmonat',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldanzmon' ),
                     array ( 'label' => 'Aktiv',
                             'name' => 'fldaktiv',
                             'width' => 20, 
                             'type' => 'YN',
                             'dbfield' => 'fldaktiv' ));

$filterarray = array ( array ( 'label' => 'Kontoinhaber:',
                             'name' => 'gruppe', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblktobanken',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'seldborder' => 'fldBez',
                             'dbfield' => 'fldid_ktogrp' ),
                      array ( 'label' => 'Dauerauftragtyp:',
                             'name' => 'fltdauerauftragtyp', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tbldauerauftragtyp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_dauerauftragtyp' ),
                      array ( 'label' => 'KtoEAtyp:',
                             'name' => 'fltktoeatyp', 
                             'width' => 1, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblktoEATyp',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_ktoeatyp' ),
                      array ( 'label' => '<br>Aktiv:',
                             'name' => 'fldaktiv', 
                             'width' => 1, 
                             'type' => 'YN',
                             'sign' => '=',
                             'dbfield' => 'fldaktiv' ));

$pararray = array ( 'headline' => 'Kostenaufstellung',
                    'dbtable' => 'tblktodauerauftrag',
                    'orderby' => 'fldid_ktoeatyp',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>