<?php

$listarray = array ( array ( 'label' => 'Nr',
                             'name' => 'nr',
                             'width' => 40, 
                             'type' => 'text',
                             'dbfield' => 'fldnr' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 500, 
                             'type' => 'text',
                             'linkfield' => 'fldlink',
                             'targetfield' => 'fldTarget',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Album',
                             'name' => 'album', 
                             'width' => 500, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'fieldprthide' => 'true',
                             'sign' => '=',
                             'dbtable' => 'tblmusic_grp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_musicgrp' ),
                     array ( 'label' => 'Noten',
                             'name' => 'noten',
                             'fieldhide' => 'true',
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldnotenfile' ),
                     array ( 'label' => 'Link',
                             'name' => 'link',
                             'fieldhide' => 'true',
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldlink' ),
                     array ( 'label' => 'Target',
                             'name' => 'target',
                             'fieldhide' => 'true',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldTarget' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'mplayer.php',
                             'dbfield' => 'icon-play' ));

$filterarray = array ( array ( 'label' => 'Album:',
                             'name' => 'fltalbum', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblmusic_grp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_musicgrp' ));

$pararray = array ( 'headline' => 'Musik',
                    'dbtable' => 'tblmusic_liste',
                    'orderby' => 'fldnr',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');

$prtarray = array ( 'headline' => 'Musikliste Ohrensausen',
                    'anzsp' => 2,
                    'maxsp' => 37);

?>