<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Geraet',
                             'name' => 'geraet',
                             'width' => 150, 
                             'type' => 'selectid',
                             'dbtable' => 'tblgeraet',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_geraet' ),
                     array ( 'label' => 'Wo',
                             'name' => 'wo',
                             'width' => 150, 
                             'type' => 'selectid',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'seldbwhere' => "fldo01typ='ZIMMER'",
                             'dbfield' => 'fldid_ort' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz',
                             'width' => 10, 
                             'type' => 'calc',
                             'dbfield' => 'fldAnz' ),
                     array ( 'label' => 'Verbrauch',
                             'name' => 'verbrauch',
                             'width' => 10, 
                             'type' => 'calcdb',
                             'arrind' => 0,
                             'calctable' => 'tblgeraet',
                             'calcfield' => 'fldAnz',
                             'calcindex' => 'fldindex',
                             'calcfaktor' => 'fldfaktor',
                             'dbindex' => 'fldid_geraet',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Preis',
                             'name' => 'zeittarif',
                             'default' => '0.115675649',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldPreis' ),
                     array ( 'label' => 'Gesamtpreis',
                             'name' => 'gesamtpreis',
                             'width' => 20, 
                             'type1' => 'calcaddsum',
                             'type' => 'calcdb',
                             'arrind' => 1,
                             'calctable' => 'tblgeraet',
                             'calcfield' => 'fldAnz',
                             'calcindex' => 'fldindex',
                             'calcfaktor' => 'fldfaktor',
                             'calcmultfield' => 'fldPreis',
                             'dbindex' => 'fldid_geraet',
                             'calcadddbfield' => 'fldPreis',
                             'calcaddfield' => 'fldAnz',
                             'dbfield' => 'fldGespreis' ),
                     array ( 'label' => 'Datum',
                             'name' => 'ablesedatum', 
                             'width' => 10, 
                             'type' => 'date',
                             'fieldhide' => 'true',
                             'default' => 'now()',
                             'dbfield' => 'fldAbleseDat' ),
                     array ( 'label' => 'Abrjahr',
                             'name' => 'jahr',
                             'showhide' => 'true',
                             'width' => 20, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tbljahr',
                             'seldbfield' => 'fldjahr',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldAbrjahr' ),
                     array ( 'label' => 'OK',
                             'name' => 'ok', 
                             'width' => 10, 
                             'type' => 'YN',
                             'default' => 'J',
                             'dbfield' => 'fldok' ));

$filterarray = array ( array ( 'label' => 'Geraet',
                               'name' => 'fltgeraet', 
                               'value' => '(ohne)',
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblgeraet',
                               'seldbfield' => 'fldbez',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldid_geraet' ),
                       array ( 'label' => 'Wo',
                               'name' => 'wo', 
                               'value' => '(ohne)',
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblorte',
                               'seldbfield' => 'fldBez',
                               'seldbindex' => 'fldIndex',
                               'selwhere' => "fldo01typ='ZIMMER'",
                               'dbfield' => 'fldid_ort' ),
                       array ( 'label' => 'Jahr',
                               'name' => 'jahr', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tbljahr',
                               'seldbfield' => 'fldjahr',
                               'dbfield' => 'fldAbrjahr' ),
                       array ( 'label' => 'OK',
                               'name' => 'ok', 
                               'width' => 10, 
                               'type' => 'YN',
                               'sign' => '=',
                               'dbfield' => 'fldok' ));
                               

$pararray = array ( 'headline' => 'Heizung',
                    'dbtable' => 'tblheizung',
                    'orderby' => '',
                    'strwhere' => "fldArchivDat=''",
                    'fldarchivdat' => 'fldArchivDat',
                    'fldEinkaufDat' => 'fldAbleseDat',
                    'fldindex' => 'fldindex');
?>