<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 30, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'S-Nr',
                             'name' => 'nummer', 
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldnummer' ),
                     array ( 'label' => 'Zimmer',
                             'name' => 'zimmer', 
                             'width' => 500, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'sign' => '=',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbaddfield' => 'fldnummer',
                             'seldbindex' => 'fldIndex',
                             'seldbwhere' => "fldo01typ='ZIMMER'",
                             'dbfield' => 'fldind_zimmer' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz', 
                             'width' => 100, 
                             'type' => 'cntind',
                             'dbselfield' => 'fldo01typ',
                             'dbselwert' => 'FACH',
                             'dbfldind' => 'fldind_moebel',
                             'dbfield' => 'fldproz' ),
                     array ( 'label' => 'Prozent',
                             'name' => 'proz', 
                             'width' => 100, 
                             'type' => 'proccalc',
                             'dbselfield' => 'fldo01typ',
                             'dbselwert' => 'FACH',
                             'dbfldind' => 'fldind_moebel',
                             'dbfield' => 'fldproz' ),
                     array ( 'label' => 'Typ',
                             'name' => 'typ',
                             'default' => 'MOEBEL',
                             'fieldhide' => 'true', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldo01typ' ));

$filterarray = array ( array ( 'label' => 'Zimmer:',
                             'name' => 'zimmer', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'selwhere' => "fldo01typ='ZIMMER'",
                             'dbfield' => 'fldind_zimmer' ));

$pararray = array ( 'headline' => 'Moebel',
                    'dbtable' => 'tblorte',
                    'orderby' => 'fldnummer',
                    'strwhere' => "fldo01typ='MOEBEL'",
                    'fldindex' => 'fldIndex');
?>