<?php
$listarray = array ( array ( 'label' => 'Host',
                             'name' => 'host',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldHost' ),
                     array ( 'label' => 'IP-Addresse',
                             'name' => 'ipaddr',
                             'width' => 50, 
                             'type' => 'ipaddr',
                             'dbfield' => 'fldIPAddr' ),                                                  
                     array ( 'label' => 'Datenbank',
                             'name' => 'datenbank',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'flddbname' ),                                                  
                     array ( 'label' => 'Art',
                             'name' => 'art',
                             'default' => 'auto',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldSyncart' ),                                                 
                     array ( 'label' => 'Username',
                             'name' => 'username',
                             'fieldhide' => 'true',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldusername' ),                                                 
                     array ( 'label' => 'Passwort',
                             'name' => 'passwort',
                             'fieldhide' => 'true',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldpassword' ),                                                 
                     array ( 'label' => 'Aktiv',
                             'name' => 'aktiv',
                             'default' => 'N',
                             'width' => 10, 
                             'type' => 'YN',
                             'dbfield' => 'fldaktiv' ),                                                 
                     array ( 'label' => 'Local',
                             'name' => 'local',
                             'default' => 'N',
                             'width' => 10, 
                             'type' => 'YN',
                             'dbfield' => 'fldlocal' ),                                                 
                     array ( 'label' => 'Cloud',
                             'name' => 'cloud',
                             'default' => 'N',
                             'width' => 10, 
                             'type' => 'YN',
                             'dbfield' => 'fldcloud' ),                                                 
                     array ( 'label' => 'Remotepfad',
                             'name' => 'remotepfad',
                             'fieldhide' => 'true',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldremotepfad' ));                                                 

$filterarray = array ( array ( 'label' => 'Aktiv:',
                             'name' => 'setaktiv', 
                             'width' => 10, 
                             'type' => 'YN',
                             'sign' => '=',
                             'dbfield' => 'fldaktiv' ));

$pararray = array ( 'headline' => 'Computer',
                    'dbtable' => 'tblcomputer',
                    'selectcomputer' => 'true1',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldIndex');
?>