<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 25, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datum2', 
                             'width' => 10, 
                             'type' => 'date',
                             'default' => 'now()',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Geschenkidee',
                             'name' => 'geschenkidee', 
                             'width' => 500, 
                             'type' => 'text',
                             'linkfield' => 'fldlink',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Preis',
                             'name' => 'preis',
                             'width' => 70, 
                             'type' => 'calc',
                             'dbfield' => 'fldpreis' ),
                     array ( 'label' => 'Link',
                             'name' => 'link', 
                             'fieldhide' => 'true',
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldlink' ),
                     array ( 'label' => 'Anlass',
                             'name' => 'anlass', 
                             'width' => 50, 
                             'type' => 'select',
                             'getdefault' => 'true',
                             'dbtable' => 'tblanlass',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldanlass' ),
                     array ( 'label' => 'f&uumlr',
                             'name' => 'fuer', 
                             'width' => 50, 
                             'type' => 'select',
                             'getdefault' => 'true',
                             'dbtable' => 'tblbeschenkte',
                             'seldbfield' => 'fldname',
                             'dbfield' => 'fldbeschenkter' ),
                     array ( 'label' => 'von',
                             'name' => 'von', 
                             'width' => 200, 
                             'type' => 'select',
                             'getdefault' => 'true',
                             'dbtable' => 'tblbeschenkte',
                             'seldbfield' => 'fldname',
                             'dbfield' => 'fldvon' ),
                     array ( 'label' => 'Status',
                             'name' => 'status', 
                             'width' => 50, 
                             'default' => 'offen',
                             'type' => 'select',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldstatus' ),
                     array ( 'label' => 'Bild',
                             'name' => 'bild', 
                             'width' => 50, 
                             'type' => 'blobid',
                             'dbfield' => 'fldimage' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'resync.php',
                             'dbfield' => 'icon-book' ));

$filterarray = array ( array ( 'label' => 'f&uumlr:',
                             'name' => 'fuer', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblbeschenkte',
                             'seldbfield' => 'fldname',
                             'dbfield' => 'fldbeschenkter' ),
                      array ( 'label' => 'von:',
                             'name' => 'von', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblbeschenkte',
                             'seldbfield' => 'fldname',
                             'dbfield' => 'fldvon' ),
                      array ( 'label' => 'Anlass:',
                             'name' => 'anlass', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblanlass',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldanlass' ),
                      array ( 'label' => 'Status:',
                             'name' => 'status', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldstatus' ));

$pararray = array ( 'headline' => 'Geschenkliste',
                    'name' => 'GIFT',
                    'dbtable' => 'tblgeschenke',
                    'orderby' => 'flddatum,fldindex',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>