<?php
$listarray = array ( array ( 'label' => 'Rezept',
                             'name' => 'rezept', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_rezepte' ),
                     array ( 'label' => 'Menge',
                             'name' => 'menge', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldmenge' ),
                     array ( 'label' => 'ME',
                             'name' => 'me', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblmengein',
                             'seldbfield' => 'fldkurz',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_me' ),
                     array ( 'label' => 'Zutat',
                             'name' => 'zutat', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Grundartikel',
                             'name' => 'grundartikel', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblgrundartikel',
                             'seldbfield' => 'fldbezmz',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_grundartikel' ));

$filterarray = array ( array ( 'label' => 'Rezept',
                             'name' => 'rezept', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_rezepte' ));

$pararray = array ( 'headline' => 'Zutaten',
                    'dbtable' => 'tblzutaten',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');

?>