<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),                     
                     array ( 'label' => 'Trigger',
                             'name' => 'settrigger',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldsettrigger' ),
                     array ( 'label' => 'Anz DS',
                             'name' => 'anzds',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldAnz' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'trigger.php',
                             'funcpara' => 'trigger=1',
                             'dbfield' => 'icon-book' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'trigger.php',
                             'funcpara' => 'trigger=5',
                             'dbfield' => 'icon-trash' ));

$filterarray = array ( array ( 'label' => 'Trigger:',
                             'name' => 'settrigger', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblsettrigger',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldsettrigger' ),
                       array ( 'label' => 'Computer',
                             'name' => 'txtcomputer', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblcomputer',
                             'seldbfield' => 'fldHost',
                             'seldbindex' => 'fldIndex',
                             'selwhere' => "fldaktiv='J'",
                             'dbfield' => 'fldid_computer' ));                             

$pararray = array ( 'headline' => 'Trigger',
                    'dbtable' => 'tbltrigger',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>