<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Webadr',
                             'name' => 'webadr',
                             'default' => 'classes/showtab.php?menu=modul',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldwebadr' ),                                                  
                     array ( 'label' => 'Sprache',
                             'name' => 'sprache',
                             'default' => 'de',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldlang' ),                                                  
                     array ( 'label' => 'Source',
                             'name' => 'source',
                             'fieldhide' => 'true', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldsource' ),                                                  
                     array ( 'label' => 'Publictyp',
                             'name' => 'publictyp',
                             'fieldhide' => 'false',
                             'width' => 10, 
                             'type' => 'selectid',
                             'dbtable' => 'tblpublictyp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_publictyp' ),
                     array ( 'label' => 'Version',
                             'name' => 'version',
                             'default' => '0303',
                             'width' => 10, 
                             'type' => 'select',
                             'dbtable' => 'tblversion',
                             'seldbfield' => 'fldkurz',
                             'dbfield' => 'fldversion' ));                                                  

$filterarray = array ( array ( 'label' => '<br>Suchen',
                               'name' => 'suchen', 
                               'width' => 10, 
                               'sign' => ' like ',
                               'type' => 'search',
                               'dbfield' => 'fldbez' ));

$pararray = array ( 'headline' => 'Modul',
                    'dbtable' => 'tblmenu_modul',
                    'orderby' => '',
                    'strwhere' => "fldversion>='0303'",
                    'fldindex' => 'fldindex');
?>