<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 20, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'R-Nr',
                             'name' => 'nummer', 
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldnummer' ),
                     array ( 'label' => 'Stockwerke',
                             'name' => 'stockwerke', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tbletagen',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_etagen' ),
                     array ( 'label' => 'Etage',
                             'name' => 'etage', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldetage' ),
                     array ( 'label' => 'Verant.',
                             'name' => 'verantwortlich', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_benutzer' ),
                     array ( 'label' => 'Max. Anzahl',
                             'name' => 'maxanz', 
                             'width' => 50, 
                             'type' => 'anzproz',
                             'fieldhide' => 'true',
                             'dbfield' => 'fldmaxanz' ),
                     array ( 'label' => 'Pr',
                             'name' => 'pr', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblprior',
                             'seldbfield' => 'fldprior',
                             'dbfield' => 'fldprior' ),
//                     array ( 'label' => 'Status',
//                             'name' => 'status', 
//                             'getdefault' => 'true',
//                             'width' => 50, 
//                             'type' => 'selectid',
//                             'dbtable' => 'tblstatus as stat,tblstat_grp as grp,tblstat_zuord as zuord',
//                             'seldbfield' => 'fldbez',
//                             'seldbindex' => 'stat.fldindex',
//                             'seldbwhere' => 'stat.fldindex=zuord.fldid_status AND grp.fldindex=zuord.fldid_grp AND grp.fldindex=43',
//                             'dbfield' => 'fldid_status' ),
                     array ( 'label' => 'Status',
                             'name' => 'status', 
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'selectid',
                             'dbtable' => 'tblstatus',
                             'viewtable' => 'viewstatuszimmer',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_status' ),
                     array ( 'label' => 'Prozent',
                             'name' => 'proz', 
                             'width' => 100, 
                             'type' => 'proccalc',
                             'dbselfield' => 'fldo01typ',
                             'dbselwert' => 'FACH',
                             'dbselwert2' => 'MOEBEL',
                             'dbfldind' => 'fldind_zimmer',
                             'dbfield' => 'fldproz' ),
                     array ( 'label' => 'Sort',
                             'name' => 'sort',
                             'fieldhide' => 'true', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldsort' ),
                     array ( 'label' => 'Typ',
                             'name' => 'typ',
                             'fieldhide' => 'true',
                             'default' => 'ZIMMER', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldo01typ' ));

$filterarray = array ( array ( 'label' => 'Stockwerke',
                             'name' => 'stockwerke', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tbletagen',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_etagen' ),
                      array ( 'label' => 'Prior:',
                             'name' => 'prior', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '>=',
                             'dbtable' => 'tblprior',
                             'seldbfield' => 'fldprior',
                             'dbfield' => 'fldprior' ),
//                      array ( 'label' => 'Status:',
//                             'name' => 'status', 
//                             'width' => 10, 
//                             'type' => 'selectid',
//                             'sign' => '=',
//                             'dbtable' => 'tblstatus as stat,tblstat_grp as grp,tblstat_zuord as zuord',
//                             'seldbfield' => 'fldbez',
//                             'seldbindex' => 'fldindex',
//                             'selwhere' => 'stat.fldindex=zuord.fldid_status AND grp.fldindex=zuord.fldid_grp AND grp.fldindex=43',
//                             'dbfield' => 'fldid_status' ),
                      array ( 'label' => 'Status:',
                             'name' => 'status', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblstatus',
                             'viewtable' => 'viewstatuszimmer',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_status' ),
                       array ( 'label' => 'Verant.',
                             'name' => 'fltuser', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_benutzer' ));

$pararray = array ( 'headline' => 'Zimmer',
                    'dbtable' => 'tblorte',
                    'orderby' => 'fldid_benutzer,fldsort',
                    'strwhere' => "fldo01typ='ZIMMER'",
                    'fldindex' => 'fldIndex');
?>