<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Farbe',
                             'name' => 'farbe', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldfarbe' ),
                     array ( 'label' => 'Bildpfad',
                             'name' => 'imagepfad', 
                             'fieldhide' => 'true',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldimagepfad' ),
                     array ( 'label' => 'JN',
                             'name' => 'jn', 
                             'width' => 5, 
                             'type1' => 'choice',
                             'type' => 'text',
                             'dbfield' => 'fldsel' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'mark.php',
                             'dbfield' => 'icon-book' ));

$filterarray = array ( array ( 'label' => 'Sel:',
                             'name' => 'askjn',
                             'value' => '', 
                             'width' => 50, 
                             'type' => 'select',
                             'sign' => '=',   
                             'dbtable' => 'tblsel',
                             'seldbfield' => 'fldbez',                           
                             'dbfield' => 'fldsel' ));

$pararray = array ( 'headline' => 'Termin-Serie',
                    'dbtable' => 'tbltermine_serie',
                    'orderby' => '',
                    'strwhere' => '',
                    'markseldb' => 'J',
                    'markselno' => 'N',
                    'marktoggle' => 'true',
                    'markfield2' => 'fldsel',
                    'fldbez' => 'fldBez',
                    'fldindex' => 'fldindex');
?>