<?php
$menu=$_GET[menu];
$menu="rezeptzutaten";
$idwert=$_GET[idwert];
$drucken="N";
include("../config.php");
$query="SELECT * FROM tblrezepte WHERE fldIndex=".$idwert;
$result = mysql_query($query) or die(mysql_error());
$line = mysql_fetch_array($result);echo "<table>";
echo "<tr>";
echo "<td><h1>".$line['fldBez']."</h1></td>";
echo "</tr>";
echo "<tr>";
echo "<td><h3>".$line['flduntertitel']."</h3></td>";
echo "</tr>";
echo "<tr>";
echo "<td>";
echo "<table>";
echo "<tr valign='top'><td>";
echo "<table>";
echo "<tr>";
echo "<td width='300'>".$line['fldzubereitung']."</td>";
echo "</tr>";
echo "<tr><td><br>";
echo "</td></tr>";
echo "<tr><td>";
echo "<table>";
echo "<tr>";
echo "<td width='50'><b>Arbeitszeit:</b></td><td style='text-align:top;'>".$line['fldarbeitszeit']."</td>";
echo "</tr>";
echo "<tr>";
echo "<td width='50'><b>Schwierigkeitsgrad:</b></td><td>".$line['fldschwierigkeit']."</td>";
echo "</tr>";
echo "<tr>";
echo "<td width='50'><b>Kalorien p. P.:</b></td><td>".$line['fldkalorien']."</td>";
echo "</tr>";
echo "</table>";
echo "</td></tr>";
echo "</table>";
echo "</td>";
echo "<td>";
echo "<table>";
echo "<tr>";
echo "<td>";
echo "	<a href=''><img src='".$line['fldbilddatei']."' width='260' height='195' alt='Rezeptbild' /></a>";
echo "</td>";
echo "</tr>";
echo "<tr>";
echo "<td><h2>Zutaten f&uumlr ".$line['fldanzpers']." Personen:</h2></td>";
echo "</tr>";
echo "<tr><td>";
echo "<table>";
$qryzutat="SELECT * FROM tblzutaten WHERE fldid_rezepte=".$idwert;
$reszutat = mysql_query($qryzutat) or die(mysql_error());
while ($linzutat = mysql_fetch_array($reszutat)) {
  $qryme="SELECT * FROM tblmengein WHERE fldindex=".$linzutat['fldid_me'];
  $resme = mysql_query($qryme) or die(mysql_error());
  $linme = mysql_fetch_array($resme);
  echo "<tr>";
  echo "<td width=100 style='text-align:right;'><b>".$linzutat['fldmenge']." ".$linme['fldkurz']."</b></td>";
  echo "<td> ".$linzutat['fldbez']."</td>";
  echo "</tr>";
}
echo "</table>";
echo "</td></tr>";
echo "</table>";
echo "</td></tr>";
echo "</table>";
echo "</td>";
echo "</tr>";
echo "</table>";
?>