<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Kurz',
                             'name' => 'kurz', 
                             'width' => 100, 
                             'type' => 'text',
                             'fieldhide' => 'true',
                             'dbfield' => 'fldkurz' ),
                     array ( 'label' => 'Gruppe',
                             'name' => 'grp', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tbltermine_grp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_terminegrp' ),
                     array ( 'label' => 'Serie',
                             'name' => 'serie', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tbltermine_serie',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_terminserie' ),
                     array ( 'label' => 'Von Datum',
                             'name' => 'vondatum', 
                             'width' => 100, 
                             'type' => 'date',
                             'dbfield' => 'fldvondatum' ),
                     array ( 'label' => 'Bis Datum',
                             'name' => 'bisdatum', 
                             'width' => 100, 
                             'type' => 'date',
                             'dbfield' => 'fldbisdatum' ));

$filterarray = array ( array ( 'label' => 'Gruppe',
                             'name' => 'gruppe', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tbltermine_grp',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_terminegrp' ),
                       array ( 'label' => 'Serie',
                             'name' => 'serie', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tbltermine_serie',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_terminserie' ),
                     array ( 'label' => '<br>Zeitraum von:',
                             'name' => 'zeitraumvon',
                             'value' => '', 
                             'width' => 500, 
                             'type' => 'date',
                             'sign' => '>=',                              
                             'dbfield' => 'fldvondatum' ),
                     array ( 'label' => 'Zeitraum bis:',
                             'name' => 'zeitraumbis',
                             'value' => '', 
                             'width' => 500, 
                             'type' => 'date',
                             'sign' => '<=',                              
                             'dbfield' => 'fldvondatum' ));

$pararray = array ( 'headline' => 'Termine',
                    'dbtable' => 'tbltermine_liste',
                    'orderby' => 'fldvondatum',
                    'strwhere' => '',
                    'fldindex' => 'fldindex',
                    'marktype' => 'date',
                    'markbgcolor' => '88ffff',
                    'unmarkbgcolor' => '999fff',
                    'marksuccess' => '1938-01-16',
                    'marksign' => '=',
                    'markfield' => 'fldvondatum');
?>