<?php
$listarray = array ( array ( 'label' => 'Antwort',
                             'name' => 'antwort',
                             'width' => 25, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Anzahl',
                             'name' => 'anz',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldanz' ),
                     array ( 'label' => 'Prozent',
                             'name' => 'proz', 
                             'width' => 150, 
                             'type' => 'procpoll',
                             'dbfldind' => 'fldid_umfrage',
                             'dbfield' => 'fldanz' ),
                     array ( 'label' => 'Umfrage',
                             'name' => 'umfrage',
                             'default' => '(ohne)',
                             'getdefault' => 'true',
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblpoll_umfragen',
                             'seldbfield' => 'fldkurz',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_umfrage' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'mark.php',
                             'funcpara' => 'vote=1',
                             'dbfield' => 'icon-book' ));


$filterarray = array ( array ( 'label' => 'Umfrage',
                               'name' => 'umfrage', 
                               'value' => '(ohne)',
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblpoll_umfragen',
                               'seldbfield' => 'fldkurz',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldid_umfrage' ));

$pararray = array ( 'headline' => 'Antworten',
                    'name' => 'antworten',
                    'dbtable' => 'tblpoll_antworten',
                    'orderby' => 'fldid_umfrage,fldanz desc',
                    'strwhere' => '',
                    'markfield' => 'fldanz',
                    'hideupdate' => 'true',
                    'fldindex' => 'fldindex');
?>