<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Wo',
                             'name' => 'wo', 
                             'value' => '(ohne)',
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'seldbwhere' => "fldo01typ='ZIMMER'",
                             'selwhere' => "fldo01typ='ZIMMER'",
                             'dbfield' => 'fldid_wo' ),
                     array ( 'label' => 'Geraetenummer',
                             'name' => 'geraetenr', 
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldgeraetenr' ),
                     array ( 'label' => 'Faktor',
                             'name' => 'faktor', 
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldfaktor' ));

$pararray = array ( 'headline' => 'Ger&aumlt',
                    'dbtable' => 'tblgeraet',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>