	<?php
$listarray = array ( array ( 'label' => 'Kategory',
                             'name' => 'kategory',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblvo_category',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_category' ),
                     array ( 'label' => 'User',
                             'name' => 'user',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_user' ),
                     array ( 'label' => 'Zimmer',
                             'name' => 'zimmer',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'seldbwhere' => "fldo01typ='ZIMMER'",
                             'dbfield' => 'fldid_zimmer' ),
                     array ( 'label' => 'Prozent',
                             'name' => 'proz', 
                             'width' => 100, 
                             'type' => 'procent',
                             'dbfield' => 'fldProz' ));

$pararray = array ( 'headline' => 'Userkategorie',
                    'dbtable' => 'tblvo_usercategory',
                    'orderby' => 'fldid_user,fldid_category',
                    'strwhere' => '',
                    'fldindex' => 'fldIndex');

?>