<?php
$listarray = array ( array ( 'label' => 'ID',
                             'name' => 'id',
                             'fieldsave' => 'false', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldindex' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'chklink' => 'true',
                             'fldlink' => 'fldpdffilename',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Adresse',
                             'name' => 'adresse', 
                             'width' => 20, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tbladr_liste',
                             'seldbfield' => 'fldcompany',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldan_ind' ),
                     array ( 'label' => 'Eintrag',
                             'name' => 'datumein', 
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'date',
                             'dbfield' => 'fldeingetragen' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datumsend', 
                             'width' => 20, 
                             'type' => 'date',
                             'dbfield' => 'fldversendet' ),
                     array ( 'label' => 'Datei',
                             'name' => 'datei', 
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldfilename' ),
                     array ( 'label' => 'Pdf-Datei',
                             'name' => 'pdfdatei', 
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldpdffilename' ),
                     array ( 'label' => 'Parent',
                             'name' => 'parent', 
                             'fieldhide' => 'truex',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldparent' ),
                     array ( 'label' => 'Sort',
                             'name' => 'sort', 
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldsort' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'pdffunc.php',
                             'dbfield' => 'icon-file' ) );

$filterarray = array (array ( 'label' => 'Zeitraum von:',
                             'name' => 'zeitraumvon',
                             'value' => '', 
                             'width' => 500, 
                             'type' => 'date',
                             'sign' => '>=',                              
                             'dbfield' => 'fldversendet' ),
                      array ( 'label' => 'Zeitraum bis:',
                             'name' => 'zeitraumbis',
                             'value' => '', 
                             'width' => 500, 
                             'type' => 'date',
                             'sign' => '<=',                              
                             'dbfield' => 'fldversendet' ));

$pararray = array ( 'headline' => 'Korrespondenz',
                    'dbtable' => 'tbldocman_brfverkehr',
                    'orderby' => '',
                    'strwhere' => '',
                    'funcpar' => 'fldpdffilename',
                    'fldindex' => 'fldindex');
?>