<?php
$listarray = array ( array ( 'label' => 'Blutdruck',
                             'name' => 'blutdruck', 
                             'width' => 80, 
                             'type' => 'blutdruck',
                             'dbfield' => 'fldblutdruck' ),
                     array ( 'label' => 'Puls',
                             'name' => 'puls', 
                             'width' => 40, 
                             'type' => 'average',
                             'dbfield' => 'fldpuls' ),
                     array ( 'label' => 'Zeitpunkt',
                             'name' => 'zeitpunkt', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblzeitpunkt',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_zeitpunkt' ),
                     array ( 'label' => 'Uhrzeit',
                             'name' => 'uhrzeit', 
                             'width' => 150, 
                             'type' => 'text',
                             'dbfield' => 'flduhrzeit' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datum', 
                             'width' => 90, 
                             'type' => 'date',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Benutzer',
                             'name' => 'benutzer', 
                             'width' => 80, 
                             'type' => 'selectid',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_benutzer' ));

$filterarray = array ( array ( 'label' => 'Zeitpunkt',
                             'name' => 'fltzeitpunkt', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblzeitpunkt',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_zeitpunkt' ),
                      array ( 'label' => 'ab',
                             'name' => 'abdatum', 
                             'width' => 10, 
                             'type' => 'date',
                             'sign' => '>=',
                             'dbfield' => 'flddatum' ));


$pararray = array ( 'headline' => 'Blutdruck',
                    'dbtable' => 'tblblutdruck',
                    'orderby' => '',
                    'fldindex' => 'fldindex');
?>