<?php

$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 10, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Erledigung',
                             'name' => 'TASK',
                             'width' => 200, 
                             'type' => 'text',
                             'dbfield' => 'fldBezeichnung' ),
                     array ( 'label' => 'Gruppe',
                             'name' => 'GROUP',
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'select',
                             'dbtable' => 'tblgrperl',
                             'seldbfield' => 'fldbez',
                             'seldborder' => 'fldbez',
                             'dbfield' => 'fldGruppe' ),
                     array ( 'label' => 'Kategorie',
                             'name' => 'kategorie',
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'select',
                             'dbtable' => 'tblkategorie',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldcategory' ),
                     array ( 'label' => 'Anz',
                             'name' => 'detail', 
                             'width' => 5, 
                             'type' => 'detail',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Pr',
                             'name' => 'pr', 
                             'getdefault' => 'true',
                             'width' => 5, 
                             'type' => 'select',
                             'dbtable' => 'tblprior',
                             'seldbfield' => 'fldprior',
                             'dbfield' => 'fldPrior' ),
                     array ( 'label' => 'Status',
                             'name' => 'status', 
                             'getdefault' => 'true',
                             'width' => 50, 
                             'type' => 'select',
                             'dbtable' => 'tblstatus',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldStatus' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datum', 
                             'width' => 50, 
                             'type' => 'date',
                             'dbfield' => 'fldDatum' ),
                     array ( 'label' => 'Erl.-Datum',
                             'name' => 'erldatum', 
                             'getdefault' => 'true',
                             'fieldhide' => 'true',
                             'fieldprthide' => 'true',
                             'width' => 50, 
                             'type' => 'date',
                             'dbfield' => 'fldErledigDat' ),
                     array ( 'label' => 'Eintrag von',
                             'name' => 'eintrag', 
                             'getdefault' => 'true',
                             'width' => 100, 
                             'type' => 'select',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldBenutzer' ),
                     array ( 'label' => 'Rang',
                             'name' => 'rang', 
                             'getdefault' => 'true',
                             'width' => 10, 
                             'fieldprthide' => 'true',
                             'type' => 'text',
                             'dbfield' => 'fldRang' ),
                     array ( 'label' => 'Bemerkung',
                             'name' => 'bemerknung',
                             'fieldhide' => 'true', 
                             'fieldprthide' => 'true',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbemerkung' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'mark.php',
                             'dbfield' => 'icon-book' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'resync.php',
                             'dbfield' => 'icon-tags' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'detailfunc.php',
                             'dbfield' => 'icon-th' ) );

$filterarray = array ( array ( 'label' => 'Status:',
                             'name' => 'status', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblstatus as stat,tblstat_grp as grp,tblstat_zuord as zuord',
                             'seldbfield' => 'fldbez',
                             'selwhere' => 'stat.fldindex=zuord.fldid_status AND grp.fldindex=zuord.fldid_grp AND grp.fldindex=3',
                             'dbfield' => 'fldStatus' ),
                      array ( 'label' => 'Prior:',
                             'name' => 'prior', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '>=',
                             'dbtable' => 'tblprior',
                             'seldbfield' => 'fldprior',
                             'dbfield' => 'fldPrior' ),
                      array ( 'label' => 'Benutzer:',
                             'name' => 'benutzer', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldBenutzer' ),
                      array ( 'label' => '<br>Gruppe:',
                             'name' => 'GROUP', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblgrperl',
                             'seldbfield' => 'fldbez',
                             'seldborder' => 'fldbez',
                             'dbfield' => 'fldGruppe' ),
                      array ( 'label' => 'Kategorie:',
                             'name' => 'kategorie', 
                             'width' => 10, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblkategorie',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldcategory' ),
                      array ( 'label' => 'ab',
                             'name' => 'abdatum', 
                             'width' => 10, 
                             'type' => 'date',
                             'sign' => '>=',
                             'dbfield' => 'fldDatum' ),
                      array ( 'label' => '<br>Suchen',
                             'name' => 'suchen', 
                             'width' => 10, 
                             'sign' => ' like ',
                             'type' => 'search',
                             'dbfield' => 'fldBezeichnung' ));

$pararray = array ( 'headline' => 'Erledigungen',
                    'name' => 'TASK',
                    'dbtable' => 'tblerledigung',
                    'markfield' => 'fldStatus', 
                    'markseldb' => 'erledigt',
                    'orderby' => 'fldRang,fldDatum DESC',
                    'strwhere' => 'fldDetailInd=0',
                    'flddetail' => 'fldDetailInd',
                    'fldindex' => 'fldIndex');

$prtarray = array ( 'headline' => 'Erledigungsliste',
                    'anzsp' => 1,
                    'maxsp' => 100);

?>