<?php
$listarray = array ( array ( 'label' => 'Index',
                             'name' => 'index', 
                             'width' => 10, 
                             'type' => 'text',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldIndex' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldb01bez' ),
                     array ( 'label' => 'Art',
                             'name' => 'art', 
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblbildart',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_art' ),
                     array ( 'label' => 'Bild',
                             'name' => 'bild', 
                             'width' => 20, 
                             'type' => 'blob',
                             'dbfield' => 'fldb01bild' ),
                     array ( 'label' => 'Filetyp',
                             'name' => 'filetyp',
                             'default' => 'image/jpeg', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldb01filetype' ),
                     array ( 'label' => 'Bild',
                             'name' => 'bild', 
                             'width' => 20, 
                             'type' => 'blobid',
                             'dbfield' => 'fldIndex' ));

$filterarray = array ( array ( 'label' => 'Art',
                               'name' => 'fltart', 
                               'value' => '(ohne)',
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblbildart',
                               'seldbfield' => 'fldbez',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldid_art' ),
                     array ( 'label' => 'Suchen',
                             'name' => 'suchen', 
                             'width' => 10, 
                             'sign' => ' like ',
                             'type' => 'search',
                             'dbfield' => 'fldb01bez' ));

$pararray = array ( 'headline' => 'Bilder',
                    'dbtable' => 'tblbilder',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldIndex');
?>