<?php
$listarray = array ( array ( 'label' => 'Index',
                             'name' => 'index', 
                             'width' => 10, 
                             'type' => 'text',
                             'fieldsave' => 'NO',
                             'dbfield' => 'fldb01index' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldb01bez' ),
                     array ( 'label' => 'Bild',
                             'name' => 'bild', 
                             'width' => 20, 
                             'type' => 'blob',
                             'dbfield' => 'fldb01bild' ),
                     array ( 'label' => 'Filetyp',
                             'name' => 'filetyp',
                             'default' => 'image/jpeg', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldb01filetype' ),
                     array ( 'label' => 'Bild',
                             'name' => 'bild', 
                             'width' => 20, 
                             'type' => 'blobid',
                             'dbfield' => 'fldb01index' ));

$pararray = array ( 'headline' => 'Bilder',
                    'dbtable' => 'tblbilder',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldb01index');
?>