<?php
$listarray = array ( array ( 'label' => 'Datum',
                             'name' => 'datum', 
                             'width' => 10, 
                             'type' => 'date',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Rang',
                             'name' => 'rang', 
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldRang' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Anwender',
                             'name' => 'anwender', 
                             'width' => 20, 
                             'type' => 'select',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldbez',
                             'dbfield' => 'fldAnwender' ),
                     array ( 'label' => 'Kitajahr',
                             'name' => 'kitajahr', 
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblkitajahr',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_kitajahr' ),
                     array ( 'label' => 'Kind',
                             'name' => 'kitauser', 
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblbenutzer',
                             'seldbfield' => 'fldfullname',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_kitauser' ),
                     array ( 'label' => 'Std',
                             'name' => 'std', 
                             'width' => 2, 
                             'type' => 'calctext',
                             'dbfield' => 'fldstunden' ));

$filterarray = array ( array ( 'label' => 'Kitajahr',
                             'name' => 'fltkitajahr', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblkitajahr',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_kitajahr' ));


$pararray = array ( 'headline' => 'Elternstunden',
                    'dbtable' => 'tblelternstunden',
                    'orderby' => 'flddatum,fldRang',
                    'strwhere' => "fldarchivdat='1900-01-01'",
                    'fldindex' => 'fldindex');
?>