<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Art',
                             'name' => 'art', 
                             'width' => 20, 
                             'type' => 'selectid',
                             'dbtable' => 'tblfillyart',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_art' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz', 
                             'width' => 20, 
                             'type' => 'calc',
                             'nachkomma' => '0', 
                             'dbfield' => 'fldanz' ),
                     array ( 'label' => 'Bild',
                             'name' => 'bild', 
                             'width' => 20, 
                             'type' => 'blob',
                             'fldbild' => 'fldb01bild',
                             'dbfield' => 'fldb01bild' ),
                     array ( 'label' => 'Filetyp',
                             'name' => 'filetyp',
                             'default' => 'image/jpeg', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldb01filetype' ),
                     array ( 'label' => 'Bild-Nr',
                             'name' => 'bildid', 
                             'width' => 20, 
                             'type' => 'blobid',
                             'dbfield' => 'fldb01bild' ));

$filterarray = array ( array ( 'label' => 'Art',
                               'name' => 'fltart', 
                               'value' => '(ohne)',
                               'width' => 10, 
                               'type' => 'selectid',
                               'sign' => '=',
                               'dbtable' => 'tblfillyart',
                               'seldbfield' => 'fldbez',
                               'seldbindex' => 'fldindex',
                               'dbfield' => 'fldid_art' ));


$pararray = array ( 'headline' => 'Filly ',
                    'dbtable' => 'tblfilly',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>