<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'name' => 'nr',
                             'width' => 30, 
                             'type' => 'text',
                             'dbfield' => 'fldnr' ),
                     array ( 'label' => 'Zeile',
                             'name' => 'arrzl',
                             'width' => 100, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblarrzl',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_arrzl' ),
                     array ( 'label' => 'Music',
                             'name' => 'music',
                             'width' => 100, 
                             'type' => 'selectid',
                             'getdefault' => 'true',
                             'dbtable' => 'tblmusic_liste',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_music' ),
                     array ( 'label' => 'Stimme',
                             'name' => 'stimme',
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblstimmen',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_stimmen' ),
                     array ( 'label' => 'Instrument',
                             'name' => 'instrument',
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblinstrument',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_instrument' ));

$filterarray = array ( array ( 'label' => 'Musik',
                             'name' => 'fltmusic', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblmusic_liste',
                             'seldbfield' => 'fldbez',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldid_music' ));

$pararray = array ( 'headline' => 'Arrangement',
                    'dbtable' => 'tblarrange',
                    'orderby' => 'fldnr',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>