<?php
$listarray = array ( array ( 'label' => 'KW',
                             'name' => 'calweek', 
                             'width' => 100, 
                             'type' => 'calweek',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'WT',
                             'name' => 'weekday', 
                             'width' => 100, 
                             'type' => 'wday',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Datum',
                             'name' => 'datum', 
                             'width' => 100, 
                             'type' => 'date',
                             'dbfield' => 'flddatum' ),
                     array ( 'label' => 'Zeit',
                             'name' => 'zeit', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldzeit' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'ifemptyselectid' => 'fldid_rezepte',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'seldblink' => 'fldLink',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Rezepte',
                             'name' => 'rezepte',
                             'fieldhide' => 'true', 
                             'default' => '(ohne)',
                             'width' => 100, 
                             'type' => 'selectid',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldBez',
                             'seldbindex' => 'fldIndex',
                             'dbfield' => 'fldid_rezepte' ),
                     array ( 'label' => 'Kalorien',
                             'name' => 'kcal', 
                             'ifemptyselectid' => 'fldid_rezepte',
                             'dbtable' => 'tblrezepte',
                             'seldbfield' => 'fldkalorien',
                             'seldbindex' => 'fldIndex',
                             'width' => 100, 
                             'type' => 'zahlid',
                             'prenumber' => '0',
                             'dbfield' => 'fldkalorien' ));

$filterarray = array ( array ( 'label' => 'Zeitraum ab:',
                             'name' => 'zeitraum', 
                             'value' => '',
                             'width' => 10, 
                             'type' => 'date',
                             'sign' => '>=',
                             'dbfield' => 'flddatum' ));

$pararray = array ( 'headline' => 'Essensplan ',
                    'dbtable' => 'tblessensplan',
                    'orderby' => 'flddatum,fldzeit',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>